# -*- coding: utf-8 -*-
# In many Markdown files, the translators alter the number of hash marks, not realizing
# that by doing so they break the Markdown heading scheme.
# For example, the header jump from level 1 with level 4 with no level 2 and 3 in between.
# Or some files start out with a level 2 header.
# This program intends to eliminate the jumps in heading levels by applying some
# informed guessing as to what the levels should have been. The algorithm is not perfect.
# The goal is to reduce the Errors and Warnings generated by the Door43 page builds
# while restoring the heading levels closer to their intended order.
# The program promotes the first heading found to a level 1,
#   and normalizes the subsequent heading levels.
# The success of the algorithm is affected by the consistency of the translator in assigning
# the original heading levels.
# All the above program behavior is optional. Set suppress1 if you don't want it.
#
# Backs up the files being modified.
# Outputs files of the same name in the same location.
#
# Additional behavior:
#   Converts malformed heading marks "# #"
#   Removes blank lines between markdown list items.
#   Leading spaces before the asterisk are also removed.
#   Assures newline at the end of the file.
#
# Also expands incomplete references to tA articles.
# For example, expands Vidi: figs_metaphor to Vidi: [[rc://*/ta/man/translate/figs-metaphor]]

import re       # regular expression module
import io
import os
import string
import sys
import substitutions

# Globals
source_dir = r"C:\DCS\Oriya\or_tn.md\mat\01"
resource_type = 'tn'
language_code = 'or'

suppress1 = False       # Suppress hash mark cleanup
suppress2 = True       # Suppress list cleanup -- SHOULD BE True FOR TRANSLATIONS THAT USE MARKDOWN SYNTAX PROPERLY
if resource_type == 'ta':
    suppress1 = True
if language_code in {'ne'}:
    suppress2 = True

nChanged = 0
max_files = 1111

filename_re = re.compile(r'\d+\.md$')  # This can change for different collections of .md files
if resource_type == 'tw':
    filename_re = re.compile(r'.*\.md$')
hash_re = re.compile(r' *(#+) +', flags=re.UNICODE)
asterisk_re = re.compile('(\n *\* .*)\n(\n *\* )', flags=re.UNICODE)    # two list items with blank line between

keystring = []      # These strings are searched to determine files that are candidates for change
keystring.append( re.compile(r'figs_', flags=re.UNICODE) )
keystring.append( re.compile(r'translate_', flags=re.UNICODE) )
keystring.append( re.compile(r'writing_', flags=re.UNICODE) )
keystring.append( re.compile(r'guidelines_', flags=re.UNICODE) )
keystring.append( re.compile(r'bita_', flags=re.UNICODE) )


def shortname(longpath):
    shortname = longpath
    if source_dir in longpath:
        shortname = longpath[len(source_dir)+1:]
    return shortname

# Converts the text a whole file at a time.
# Removes blank lines between list items.
def fixLists(alltext):
    # Multiple replacements per file
    found = asterisk_re.search(alltext)
    while found:
        alltext = alltext[0:found.start()] + found.group(1) + found.group(2) + alltext[found.end():]
        found = asterisk_re.search(alltext)
    return alltext

# Calculates and returns the new header level.
# Updates the truelevel list.
def shuffle(truelevel, nmarks, currlevel):
    newlevel = currlevel
    if nmarks > currlevel and truelevel[nmarks] > currlevel:
        newlevel = currlevel + 1
    elif truelevel[nmarks] < currlevel:
        newlevel = truelevel[nmarks]
    
    # Adjust the array
    while nmarks > 1 and truelevel[nmarks] > newlevel:
        truelevel[nmarks] = newlevel
        nmarks -= 1
    return newlevel    

# Normalizes markdown heading levels.
# Removes training blanks from header lines.
def fixHeadingLevels(str):
    nChanges = 0
    text = ""
    lines = str.splitlines()
    currlevel = 0
    truelevel = [0,1,2,3,4,5,6,7,8,9]
        # each position in the array represents the calculate true header level for that number of hash marks.
        # To start, the number of hash marks is assumed to be the true level.
        # This array is modified by the shuffle() function.

    for line in lines:
        header = hash_re.match(line, 0)
        if header:
            nmarks = len(header.group(1))
            newlevel = shuffle(truelevel, nmarks, currlevel)
            if newlevel != nmarks:
                line = '#' * newlevel + ' ' + line[header.end():]
                nChanges += 1
            currlevel = newlevel
        text += line.rstrip() + '\n'
    return text

inlinekey = []      # These are the strings that are actually replaced
inlinekey.append( re.compile(r'[\:\( ]figs_(\w*)', flags=re.UNICODE) )
inlinekey.append( re.compile(r'[\:\( ]translate_(\w*)', flags=re.UNICODE) )
inlinekey.append( re.compile(r'[\:\( ]writing_(\w*)', flags=re.UNICODE) )
inlinekey.append( re.compile(r'[\:\( ]guidelines_(\w*)', flags=re.UNICODE) )
inlinekey.append( re.compile(r'[\:\( ]bita_(\w*)', flags=re.UNICODE) )
newstring = []
newstring.append( 'figs-' )
newstring.append( 'translate-' )
newstring.append( 'writing-' )
newstring.append( 'guidelines-' )
newstring.append( 'bita-' )

# Replaces primitive tA links (those that match something in inlinekey[])
def fixTaLinks(str):
    text = ""
    count = 0
    lines = str.splitlines()
    for line in lines:
        count += 1
        for i in range(len(inlinekey)):
            good_ref = ' [[rc://*/ta/man/translate/' + newstring[i]
            sub = inlinekey[i].search(line)
            while sub:
                line = line[0:sub.start()] + good_ref + sub.group(1) + ']]' + line[sub.end():]
                sub = inlinekey[i].search(line)
        text += line + '\n'
    return text

blanks_re = re.compile('[\n \t]+')     # multiple newlines/ white space at beginning of string
endblank_re = re.compile('[\n \t]{2,}\Z')     # multiple newlines/ white space at end of string
jams_re = re.compile(r'\n#+[^ \t#]', re.UNICODE)    # hash(es) at beginning of line not followed by space
#jams2_re = re.compile(r'\n\*[^ \t\*]', re.UNICODE)   # single asterisk at beginning of line not follow by space

# Does some simple cleanup operations before starting the heavy conversions.
def preliminary_cleanup(text):
    if resource_type != 'ta':
        if found := blanks_re.match(text):
            text = text[found.end():] + '\n'    # remove blanks at beginning of string
    if found := endblank_re.search(text):
        text = text[0:found.start()] + '\n'     # remove blank lines at end of string
    if not text.endswith("\n"):
        text += "\n"
    text = text.replace("# #", "##")
    found = jams_re.search(text)
    while found:
        text = text[:found.end()-1] + ' ' + text[found.end()-1:]    # add space after mark at beginning of lines
        found = jams_re.search(text)
#    found = jams2_re.search(text)      # Removed 11/16/20 because sometimes the no-space is intended (for italics)
#    while found:
#        text = text[:found.end()-1] + ' ' + text[found.end()-1:]
#        found = jams2_re.search(text)
    return text

# Applies the substitutions found in substitutions.py, plus one that is language specific
def substitution(text):
    substitutions.subs.append(	("rc://" + language_code + "/", "rc://*/") )
    for pair in substitutions.subs:
        text = text.replace(pair[0], pair[1])
    return text

# Reads the entire file as a string and converts it.
def convertFile(path):
    global nChanged
    global suppress1
    input = io.open(path, "tr", encoding="utf-8-sig")
    text = input.read()
    input.close()

    origtext = text
    text = preliminary_cleanup(text)
    text = substitution(text)
    if not text.startswith("# "):
        sys.stdout.write(shortname(path) + " does not begin with level 1 heading, so no headings will be touched.\n")
        suppress1 = True

    # Do the hash level fixes and TA references
    if "## " in text and not suppress1:
        text = fixHeadingLevels(text)

    # I took out this code 11/16/20 since it appears that the markdown dialect that we support allows blank
    # lines between list items.
    #    if asterisk_re.search(text) and not suppress2:
    #        text = fixLists(text)

    # Expand the TA links
    convertme = False
    for key in keystring:
        if key.search(text):
            convertme = True
            break
    if convertme:
        text = fixTaLinks(text)
    
    if text!= origtext:
        if len(text) < len(origtext) * 0.95:
            sys.stderr.write("Error processing " + shortname(path) + '\n')
        else:
            nChanged += 1
            bakpath = path + ".orig"
            if not os.path.isfile(bakpath):
                os.rename(path, bakpath)
            output = io.open(path, "tw", encoding='utf-8', newline='\n')
            output.write(text)
            output.close()
            sys.stdout.write("Changed: " + shortname(path) + '\n')

# Recursive routine to convert all files under the specified folder
def convertFolder(folder):
    global nChanged
    global max_files
    if nChanged >= max_files:
        return
#    sys.stdout.write("Processing " + shortname(folder) + '\n')
#    sys.stdout.flush()
    for entry in os.listdir(folder):
        path = os.path.join(folder, entry)
        if os.path.isdir(path) and entry[0] != '.':
            convertFolder(path)
        elif filename_re.match(entry):
            convertFile(path)
        if nChanged >= max_files:
            break

if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] != 'hard-coded-path':
        source_dir = sys.argv[1]

    if source_dir and os.path.isdir(source_dir):
        convertFolder(source_dir)
        sys.stdout.write("Done. Changed " + str(nChanged) + " files.\n")
    elif os.path.isfile(source_dir):
        path = source_dir
        source_dir = os.path.dirname(path)
        convertFile(path)
    else:
        sys.stderr.write("Usage: python md_cleanup.py <folder>\n  Use . for current folder or hard code the path.\n")
