# -*- coding: utf-8 -*-
# substitutions module, used by translate.py.
# An ordered list of tuples to be used for string substitutions.

subs = [
	("[Genesis", "[Postanak"),
    ("[Exodus", "[Izlazak"),
    ("[Leviticus", "[Levitski zakonik"),
    ("[Numbers", "[Brojevi"),
    ("[Deuteronomy", "[Ponovljeni zakon"),
    ("[Joshua", "[Jošua"),
    ("[Judges", "[Suci"),
    ("[Ruth", "[Ruta"),
    ("[1 Samuel", "[1 Samuelova"),
    ("[2 Samuel", "[2 Samuelova"),
    ("[1 Kings", "[1 Kraljevima"),
    ("[2 Kings", "[2 Kraljevima"),
    ("[1 Chronicles", "[1 Ljetopisa"),
    ("[2 Chronicles", "[2 Ljetopisa"),
    ("[Ezra", "[Ezra"),
    ("[Nehemiah", "[Nehemija"),
    ("[Esther", "[Estera"),
    ("[Job", "[Job"),
    ("[Psalm", "[Psalmi"),
    ("[Psalms", "[Psalmi"),
    ("[Proverbs", "[Mudre izreke"),
    ("[Ecclesiastes", "[Propovjednik"),
    ("[Song of Solomon", "[Pjesma nad pjesmama"),
    ("[Song of Songs", "[Pjesma nad pjesmama"),
    ("[Isaiah", "[Izaija"),
    ("[Jeremiah", "[Jeremija"),
    ("[Lamentations", "[Tužaljke"),
    ("[Ezekiel", "[Ezekiel"),
    ("[Daniel", "[Daniel"),
    ("[Hosea", "[Hošea"),
    ("[Joel", "[Joel"),
    ("[Amos", "[Amos"),
    ("[Obadiah", "[Obadija"),
    ("[Jonah", "[Jona"),
    ("[Micah", "[Mihej"),
    ("[Nahum", "[Nahum"),
    ("[Habakkuk", "[Habakuk"),
    ("[Zephaniah", "[Sefanija"),
    ("[Haggai", "[Hagaj"),
    ("[Zechariah", "[Zaharija"),
    ("[Malachi", "[Malahija"),
    ("[Matthew", "[Matej"),
    ("[Mark", "[Marko"),
    ("[Luke", "[Luka"),
    ("[John", "[Ivan"),
    ("[Acts", "[Djela apostolska"),
    ("[Romans", "[Rimljanima"),
    ("[1 Corinthians", "[1 Korinćanima"),
    ("[2 Corinthians", "[2 Korinćanima"),
    ("[Galatians", "[Galaćanima"),
    ("[Ephesians", "[Efežanima"),
    ("[Philippians", "[Filipljanima"),
    ("[Colossians", "[Kološanima"),
    ("[1 Thessalonians", "[1 Solunjanima"),
    ("[2 Thessalonians", "[2 Solunjanima"),
    ("[1 Timothy", "[1 Timoteju"),
    ("[2 Timothy", "[2 Timoteju"),
    ("[Titus", "[Titu"),
    ("[Philemon", "[Filemonu"),
    ("[Hebrews", "[Hebrejima"),
    ("[James", "[Jakovljeva"),
    ("[1 Peter", "[1 Petrova"),
    ("[2 Peter", "[2 Petrova"),
    ("[1 John", "[1 Ivanova"),
    ("[2 John", "[2 Ivanova"),
    ("[3 John", "[3 Ivanova"),
    ("[Jude", "[Judina"),
    ("[Revelation", "[Otkrivenje")
]