#!/usr/bin/env sh
# -*- coding: utf8 -*-
#
#  Copyright (c) 2014 unfoldingWord
#  http://creativecommons.org/licenses/MIT/
#  See LICENSE file for details.
#
#  Contributors:
#  Jesse Griffin <jesse@distantshores.org>

NOTES=/var/www/vhosts/door43.org/httpdocs/data/gitrepo/pages/en/bible/notes

book_import () {
    # $1 is book short name
    # $2 is number of chapters

    for x in `seq -f "%02g" 1 $2`; do
        /var/www/vhosts/door43.org/tools/uwb/ep_chunk.py en-ulb-$1-$x >/dev/null
    done

    cd $NOTES/$1
    git add .
    git commit -am "Updated $1 notes"
    git push origin master

}

book_import luk 24
book_import rut 4
book_import tit 3

chown -R apache:apache /var/www/vhosts/door43.org/httpdocs/data/gitrepo/pages/en
