#!/bin/bash

###############################################################################
#
#  `plaintext_export` is a script that exports the complete text of Open
#  Bible Stories in every language on Door43 (in which it is available) as
#  plain text and ODT.
#
#  It is intended to help facilitate the recording of the audio files for
#  Open Bible Stories
#
###############################################################################

ROOT=/var/www/vhosts/door43.org/httpdocs/data/gitrepo/pages
FILE=$ROOT/en/obs/01-the-creation.txt
TMP=tmpfile.txt

#
# remove extra info from images
#
cat $FILE | \
sed 's/\&640x360//g' > $TMP

#
# convert wiki text --> HTML --> ODT
#
doku2html $TMP | \
sed 's/_media/var\/www\/vhosts\/door43\.org\/httpdocs\/data\/media/g' | \
pandoc -f html -s -t odt -o file.odt
