#!/usr/bin/env bash
# -*- coding: utf8 -*-
#
#  Copyright (c) 2015 unfoldingWord
#  http://creativecommons.org/licenses/MIT/
#  See LICENSE file for details.
#
#  Contributors:
#  Richard Mahn <richard_mahn@wycliffeassociates.org>
#
# Array of Bible books keyed by book code

declare -A BOOK_NAMES
BOOK_NAMES=(
    ['gen']='Genesis'
    ['exo']='Exodus'
    ['lev']='Leviticus'
    ['num']='Numbers'
    ['deu']='Deuteronomy'
    ['jos']='Joshua'
    ['jdg']='Judges'
    ['rut']='Ruth'
    ['1sa']='1 Samuel'
    ['2sa']='2 Samuel'
    ['1ki']='1 Kings'
    ['2ki']='2 Kings'
    ['1ch']='1 Chronicles'
    ['2ch']='2 Chronicles'
    ['ezr']='Ezra'
    ['neh']='Nehemiah'
    ['est']='Esther'
    ['job']='Job'
    ['psa']='Psalms'
    ['pro']='Proverbs'
    ['ecc']='Ecclesiastes'
    ['sng']='Song of Solomon'
    ['isa']='Isaiah'
    ['jer']='Jeremiah'
    ['lam']='Lamentations'
    ['ezk']='Ezekiel'
    ['dan']='Daniel'
    ['hos']='Hosea'
    ['jol']='Joel'
    ['amo']='Amos'
    ['oba']='Obadiah'
    ['jon']='Jonah'
    ['mic']='Micah'
    ['nam']='Nahum'
    ['hab']='Habakkuk'
    ['zep']='Zephaniah'
    ['hag']='Haggai'
    ['zec']='Zechariah'
    ['mal']='Malachi'
    ['mat']='Matthew'
    ['mrk']='Mark'
    ['luk']='Luke'
    ['jhn']='John'
    ['act']='Acts'
    ['rom']='Romans'
    ['1co']='1 Corinthians'
    ['2co']='2 Corinthians'
    ['gal']='Galatians'
    ['eph']='Ephesians'
    ['php']='Philippians'
    ['col']='Colossians'
    ['1th']='1 Thessalonians'
    ['2th']='2 Thessalonians'
    ['1ti']='1 Timothy'
    ['2ti']='2 Timothy'
    ['tit']='Titus'
    ['phm']='Philemon'
    ['heb']='Hebrews'
    ['jas']='James'
    ['1pe']='1 Peter'
    ['2pe']='2 Peter'
    ['1jn']='1 John'
    ['2jn']='2 John'
    ['3jn']='3 John'
    ['jud']='Jude'
    ['rev']='Revelation'
)

declare -A BOOK_NUMBERS
BOOK_NUMBERS=(
    ['gen']='01'
    ['exo']='02'
    ['lev']='03'
    ['num']='04'
    ['deu']='05'
    ['jos']='06'
    ['jdg']='07'
    ['rut']='08'
    ['1sa']='09'
    ['2sa']='10'
    ['1ki']='11'
    ['2ki']='12'
    ['1ch']='13'
    ['2ch']='14'
    ['ezr']='15'
    ['neh']='16'
    ['est']='17'
    ['job']='18'
    ['psa']='19'
    ['pro']='20'
    ['ecc']='21'
    ['sng']='22'
    ['isa']='23'
    ['jer']='24'
    ['lam']='25'
    ['ezk']='26'
    ['dan']='27'
    ['hos']='28'
    ['jol']='29'
    ['amo']='30'
    ['oba']='31'
    ['jon']='32'
    ['mic']='33'
    ['nam']='34'
    ['hab']='35'
    ['zep']='36'
    ['hag']='37'
    ['zec']='38'
    ['mal']='39'
    ['mat']='40'
    ['mrk']='41'
    ['luk']='42'
    ['jhn']='43'
    ['act']='44'
    ['rom']='45'
    ['1co']='46'
    ['2co']='47'
    ['gal']='48'
    ['eph']='49'
    ['php']='50'
    ['col']='51'
    ['1th']='52'
    ['2th']='53'
    ['1ti']='54'
    ['2ti']='55'
    ['tit']='56'
    ['phm']='57'
    ['heb']='58'
    ['jas']='59'
    ['1pe']='60'
    ['2pe']='61'
    ['1jn']='62'
    ['2jn']='63'
    ['3jn']='64'
    ['jud']='65'
    ['rev']='66'
)
