# -*- coding: utf-8 -*-
# GUI interface for selecting a process to perform in the USFM Wizard.

from tkinter import *
from tkinter import ttk
from tkinter import font
from idlelib.tooltip import Hovertip
import os
import g_step

stepname = 'SelectProcess'   # equals the main class name in this module

class SelectProcess(g_step.Step):
    def __init__(self, mainframe, mainapp):
        super().__init__(mainframe, mainapp, stepname, "Start")
        self.frame = Select_Frame(mainframe, self)
        self.frame.grid(row=1, column=0, sticky="nsew")

    def onNext(self):
        self.mainapp.set_process(self.values['selection'])
        self.mainapp.step_next()

class Select_Frame(ttk.Frame):
    def __init__(self, parent, controller):
        super().__init__(parent)
        self.controller = controller

        self.process = StringVar()        
        subheadingFont = font.Font(size=10, slant='italic')     # normal size is 9
        suppressions_label = ttk.Label(self, text="What do you want to do today?", font=subheadingFont)
        suppressions_label.grid(row=3, column=1, columnspan=2, sticky=W, pady=(4,2))

        process1_rb = ttk.Radiobutton(self, text='Convert text to USFM', variable=self.process,
                                      command=self._onRbChange, value='Txt2USFM')
        process1_rb.grid(row=4, column=1, sticky=W)
        process1_Tip = Hovertip(process1_rb, hover_delay=500,
             text="Convert a set of text files from BTT-Writer repos to USFM.")

        process2_rb = ttk.Radiobutton(self, text='Verify and clean USFM', variable=self.process,
                                      command=self._onRbChange, value='VerifyUSFM')
        process2_rb.grid(row=5, column=1, sticky=W)
        process2_Tip = Hovertip(process2_rb, hover_delay=500,
             text="Verify and/or clean up existing USFM file.")

        process3_rb = ttk.Radiobutton(self, text='Convert plain text to USFM', variable=self.process,
                                      command=self._onRbChange, value='Plaintext2Usfm')
        process3_rb.grid(row=6, column=1, sticky=W)
        process3_Tip = Hovertip(process3_rb, hover_delay=500,
             text="Convert plain text file containing books of the Bible to usfm files.")

        process4_rb = ttk.Radiobutton(self, text='Convert USFM to USX', variable=self.process,
                                      command=self._onRbChange, value='Usfm2Usx')
        process4_rb.grid(row=7, column=1, sticky=W)
        process4_Tip = Hovertip(process4_rb, hover_delay=500,
             text="Produce a BTTW-compatible resource container from USFM.")

        self.columnconfigure(1, minsize=505)
        self.rowconfigure(88, minsize=150, weight=1)  # let the message expand vertically

        self.message_area = Text(self, height=10, width=60, wrap="word")
        self.message_area['borderwidth'] = 2
        self.message_area['relief'] = 'sunken'
        self.message_area['background'] = 'grey97'
        self.message_area.grid(row=88, column=1, sticky='nsew', pady=6)

        ys = ttk.Scrollbar(self, orient = 'vertical', command = self.message_area.yview)
        ys.grid(column = 5, row = 88, sticky = 'ns')
        self.message_area['yscrollcommand'] = ys.set

    # Called when the frame is first activated. Populate the initial values.
    def show_values(self, values):
        self.values = values
        self.process.set(values['selection'])
        self._explain()
        self.controller.showbutton(psn=5, text=">>>",
                              tip="Begin the process you selected above.", cmd=self._onNext)
        self.controller.hidebutton(1,2,3,4)
        self._set_button_status()

    # Caches the current selection in self.values and calls the mainapp to save in the config file.
    def _save_values(self):
        self.values['selection'] = self.process.get()
        self.controller.mainapp.save_values(stepname, self.values)
        # self._set_button_status()

    # Handles the radio button click event.
    def _onRbChange(self, *args):
        self._explain()
        self._set_button_status()

    def _onNext(self, *args):
        self._save_values()
        self.controller.onNext()

    # Presents a detailed message about the selected process.
    def _explain(self, *args):
        self.message_area['state'] = NORMAL   # enables insertions to message area
        self.message_area.delete('1.0', 'end')
        match self.process.get():
            case 'Txt2USFM':
                self.message_area.insert('end',
"The “Convert text to USFM” process merges text files generated by BTT-Writer and converts them to USFM.\n\n\
It parses the manifest.json files to get the book ID and contributor names, and parses title.txt files to get the book titles. \
It creates one USFM file per book, with a proper header. \
The resulting files have standardized names, like 41-MAT.usfm and 42-MRK.usfm. \
It converts multiple books at once if there are multiple books.\n\n\
The resulting USFM file(s) need to be verified and probably cleaned up a bit.")
            case 'VerifyUSFM':
                self.message_area.insert('end', "Find and address issues in USFM files.")
            case 'Plaintext2Usfm':
                self.message_area.insert('end', "This process is not supported yet.")
            case 'Usfm2Usx':
                self.message_area.insert('end',
"This process produces .usx and auxiliary files from USFM source text. \
This creates a “resource container” which BTT-Writer can then use as a new source text.\n\n\
Chunk boundaries are based on \s5 markers in the USFM files. \
The input file(s) should be verified, correct USFM. Therefore, the first step of this process is to validate the USFM files.")
            case _:
                self.message_area.insert(f"Internal error: process {self.process.get()} is not handled.")
        self.message_area.see('1.0')
        self.message_area['state'] = DISABLED   # prevents editing of message area

    def _set_button_status(self):
        okay = self.process.get() in {'Txt2USFM', 'VerifyUSFM', 'Usfm2Usx'}
        self.controller.enablebutton(5, okay)
